//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiniao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opiniao()
        {
            this.Aula = new HashSet<Aula>();
        }
    
        public int ID { get; set; }
        public int Avaliacao { get; set; }
        public string Texto { get; set; }
        public int Professor_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aula> Aula { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
